<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="icon" href=".sistema/icones/weather_sun.png" type="image/x-icon" />
        <link type="text/css" rel="stylesheet" href=".sistema/temas/bootstrap3/css/bootstrap.css" media="screen"/>
        <title></title>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand js-nome-sistema" href="#">FrameCalixto</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="btn-menu-sistema"><a href="#"><span class="glyphicon glyphicon-menu-hamburger"></span></a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="js-menu-sistema">
        <div class="container">
            <div class="col-sm-8">
                <fieldset>
                    <legend>Funcionaliddes</legend>
                    <ul class="nav nav-pills">
                        <li role="presentation"><a href="#">Home</a></li>
                        <li role="presentation"><a href="#">Profile</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                    </ul>
                </fieldset>
                <fieldset>
                    <legend>Utilitários</legend>
                    <ul class="nav nav-pills">
                        <li role="presentation"><a href="#">Home</a></li>
                        <li role="presentation"><a href="#">Profile</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                    </ul>
                </fieldset>
                
            </div>
            <fieldset class="col-sm-4">
                <legend data-html-nmUsuario >usuario.padrao@framecalixto.com</legend>
                <ul class="nav nav-stacked">
                    <li role="presentation"><a href="#">Dados Pessoais</a></li>
                    <li role="presentation"><a href="#">Alterar Senha</a></li>
                    <li role="presentation"><a href="#">Mensagens</a></li>
                </ul>
            </fieldset>
        </div>
    </div>
    <div class="js-tela-ajax"></div>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/jquery-2.1.4.min.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/bootstrap.min.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/noty/jquery.noty.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/noty/layouts/bottomRight.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/noty/themes/bootstrap.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/visao.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/js/sistema.js"></script>
    <script language="javascript" type="text/javascript" src=".sistema/temas/bootstrap3/boot.js"></script>
</body>
</html>