<div class="container">
    <?php echo $mensageria;?>
    <form name="formulario" method="post" action="<?php echo $action;?>" class="form-horizontal well">
        <h4 class="fc-titulo-especifico">Recuperação de senha</h4>
        <hr/>
        <div class="fc-campo-grupo">
            <div class="fc-campo-subgrupo">
                <div class="fc-campo control-group">
                    <label for="email" class="control-label">Email:</label>
                    <span class=""><input type="email" autocomplete="off" name="emailUsuario" title="Digite seu email para recuperar sua senha" /></span>
                </div>
			</div>
            <div id='fc-menu_corpo'>
				<button class="btn btn-primary">Recuperar minha senha</button>
            </div>
        </div>
    </form>
</div>
