<form name="formulario" method="post" action="<?php echo $action;?>">
	<div class="container0">
		<div class="a"></div>
		<div class="b"></div>
		<div class="c"></div>
		<div class="d"></div>
		<div class="e"></div>
		<div class="f"></div>
		<div class="g"></div>
		<div class="h"></div>
		<h1 class="titulo">&nbsp;</h1>
		<div class="texto">
			<?php echo $idUsuario;?>
			<div class="tabela2">
				<div class='campo'>
					<label for='<?php echo $idPessoa->pegarId();?>'><?php echo $nomeIdPessoa;?>:</label>
					<span><?php echo $idPessoa;?></span>
				</div>
				<div class='campo'>
					<label><?php echo $nomeNmUsuario;?>:</label>
					<span><?php echo $nmUsuario;?></span>
				</div>
				<div class='campo'>
					<label><?php echo $nomeNmSenha;?>:</label>
					<span><?php echo $nmSenha;?></span>
				</div>
				<div class='campo'>
					<label><?php echo $nomeStatus;?>:</label>
					<span><?php echo $status;?></span>
				</div>
				<div class='campo'>
					<label><?php echo $nomeDtCadastro;?>:</label>
					<span><?php echo $dtCadastro;?></span>
				</div>
			</div>
	        <div id='menu_corpo'>
	            <?php echo $menuPrograma;?>
	        </div>
		</div>
	</div>
</form>