<div class="container">
    <form name="formulario" method="post" data-attr-action="action" class="well">
        <fieldset>
            <legend data-html-tituloEspecifico ></legend>
            <div class="control-group">
                <label class="control-label"><i class="icon-user"></i><span data-html-nomeNmLogin ></span>:</label>
                <div class="controls">
                    <input type="text" class="form-control" name="nmLogin" />
                </div>
            </div>			
            <div class="control-group">
                <label class="control-label"><i class="icon-lock"></i><span data-html-nomeNmSenha ></span>:</label>
                <div class="controls">
                    <input type="password" class="form-control" name="nmSenha" />
                </div>
            </div>			
            <div class="control-group">
                <div class="controls">
                    <button type="submit" >Enviar</button>
                    <a href="?c=CUsuario_verEsqueciSenha" class="btn">Esqueci minha senha</a>
                    <a href="?c=CUsuario_verNovo" class="btn">Não possuo cadastro</a>
                </div>
            </div>			
        </fieldset>
    </form>
</div>