<!---------------------- TEMPLATE PADRÃO ---------------------->
<div class="container">
	<?php echo '<?php echo '; ?>$mensageria«rdelim»
	<form name="formulario" method="post" action="<?php echo '<?php echo '; ?>$action«rdelim»" class="form-horizontal well">
		<h4 class="fc-titulo-especifico"><?php echo '<?php echo '; ?>$tituloEspecifico«rdelim»</h4>
		<hr/>
		<div class="fc-campo-grupo">
			<?php echo '<?php echo '; ?>$«$chaveNegocio»<?php echo ';?> '; ?>
			<div class="fc-campo-subgrupo"><?php foreach ($nomes as $indice => $propriedade): ;?>
				<div class="fc-campo control-group">
					<label for="«$propriedade»" class="control-label"><?php echo '<?php echo '; ?>$<?php echo $indice;?><?php echo ';?> '; ?>:</label>
					<span class=""><?php echo '<?php echo '; ?>$<?php echo $propriedade;?><?php echo ';?> '; ?></span>
				</div><?php endforeach;?>
			</div>
			<div id='fc-menu_corpo'>
				<?php echo '<?php echo '; ?>$menuPrograma<?php echo ';?> '; ?>
			</div>
		</div>
	</form>
</div>
<!---------------------- TEMPLATE PADRÃO ---------------------->