<script type="text/javascript" language="javascript">
function marcar(valor,controle) {
	valor = valor || false;
	controle = controle || false;
	if(controle){
		var re = new RegExp('^' + controle + '');
		for ( var i=0; i < document.formulario.elements.length; i++ ) {
			var componente = document.formulario.elements[i];
			if ( componente.type == "checkbox") {
				var res = re.exec(componente.value);
				if(res) componente.checked = valor;
			}
		}
	}else{
		for ( var i=0; i < document.formulario.elements.length; i++ ) {
			var componente = document.formulario.elements[i];
			if ( componente.type == "checkbox") {
				componente.checked = valor;
			}
		}
	}
}
</script>
<div class="container">
	<?php echo $mensageria;?>
<form name="formulario" method="post" action="<?php echo $action;?>">
	<div class="fc-pesquisa">
		<h4 class="fc-titulo-especifico"><?php echo $tituloEspecifico;?></h4>
		<div class="fc-campo-grupo">
			<div class="fc-campo-subgrupo well well-small">
				<div class='fc-campo'>
					<label><?php echo $nomeNmPerfil;?>:</label>
					<span><?php echo $idPerfil;?><?php echo $nmPerfil;?></span>
				</div>
			</div>
	        <div id='fc-menu-corpo'>
	            <?php echo $menuPrograma;?>
	        </div>
		</div>
		<div class="fc-listagem-grupo">
			<h5 class="fc-listagem-titulo"><img src=".sistema/icones/application_view_list.png" />
				(<a href='javascript:marcar(false);'>Nenhum</a>/<a href='javascript:marcar(true);'>Todos</a>)
				Acessos
			</h5>
			<div class="fc-listagem">
				<table class="table table-striped table-bordered table-hover table-condensed">
					<thead>
						<tr>
							<th>Entidade</th>
							<th colspan="2">Acesso</th>
							<th>Descrição</th>
						</tr>
					</thead>
					<tbody>
					<?php echo $listagem;?>
					</tbody>
			</table>
		</div>
	</div>
</form>
</div>
