<div class="container">
	<form name="formulario" method="post" action="<?php echo $action;?>" >
		<div>
			<h4><?php echo $tituloEspecifico;?></h4>
			<hr/>
			<div id='menu_corpo'>
				<?php echo $menuPrograma;?>
			</div>
			<table class="table table-striped table-bordered table-hover table-condensed">
				<thead>
					<tr>
						<th class="nomeEntidade">Entidade</th>
						<th class="nomeNegocio">Negócio</th>
						<th class="nomeTabela">Tabela</th>
						<th class="nomeSequence">Sequence</th>
						<th class="existente centralizado">Campos Banco</th>
						<th class="definido centralizado">Campos Entidade</th>
						<th class="definido centralizado"></th>
						<th class="centralizado"></th>
						<th class="centralizado"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($listagem as $negocio => $nome): ?>
					<tr>
						<td class="nomeEntidade"><?php echo $nome;?> </td>
						<td class="nomeNegocio"><?php echo $negocios[$negocio];?></td>
						<td class="nomeTabela"><a title="Definição da tabela '<?php echo $tabelas[$negocio];?>' no banco de dados" href="?c=CUtilitario_verListarCamposTabela&tabela=<?php echo $tabelas[$negocio];?>"><?php echo $tabelas[$negocio];?> </a></td>
						<td class="nomeSequence"><?php echo $sequencias[$negocio];?> </td>
						<td class="numerico direita"><?php echo $camposExistentes[$negocio];?></td>
						<td class="numerico direita"><?php echo $camposDefinidos[$negocio];?></td>
						<td align="left" ><?php echo $diferencas[$negocio];?></td>
						<td class="centralizado"><a href="?c=<?php echo $controles[$negocio];?>" title="Ver Tela de Pesquisa dessa Entidade"><i class="icon-th-list"></i></td>
						<td class="centralizado"><a href="?c=CUtilitario_verGeradorEntidade&amp;entidade=<?php echo $negocio;?>" title="Editar essa Entidade"><i class="icon-pencil"></i></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</form>
</div>