<div class="container">
	<form name="formulario" method="post" action="<?php echo $action;?>" >
		<div class="fc-pesquisa">
			<h4 class="fc-titulo-especifico"><?php echo $tituloEspecifico;?></h4>
			<hr/>
			<div id='menu_corpo'>
				<?php echo $menuPrograma;?>
			</div>
			<!--<div>Gerar <a href="?c=CUtilitario_gerarTodosCadastros">todos</a> os cadastros de todas as tabelas.</div>-->
			<table class="table table-striped table-bordered table-hover table-condensed">
				<thead>
					<tr>
						<th>Tabela</th>
						<th class="span2"></th>
						<th class="span1"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($listagem as $nome):?>
					<tr>
						<td><?php echo $nome;?></td>
						<td><a href="?c=CUtilitario_verGeradorEntidade&tabela=<?php echo $nome;?>" ><i class="icon-star"></i> Gerar cadastro</a></td>
						<td><a href="?c=CUtilitario_verListarCamposTabela&tabela=<?php echo $nome;?>" ><i class="icon-eye-open"></i> Ver</a></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</form>
</div>