<div class="container">
	<div>
		<h4 class="fc-titulo-especifico"><?php echo $tituloEspecifico;?><span style="font-weight:bold;"><?php echo $tabela;?></span></h4>
		<hr/>
		<table summary="text" class="table table-bordered table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th class="ui-state-default">Campo</th>
					<th class="ui-state-default">Tipo</th>
					<th class="ui-state-default">Tamanho</th>
					<th class="ui-state-default">PK</th>
					<th class="ui-state-default">Esquema FK</th>
					<th class="ui-state-default">Tabela FK</th>
					<th class="ui-state-default">Campo FK</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($listagem as $nome):?>
				<tr title="<?php echo $nome['descricao'];?>" >
					<td class="campo1"><?php echo $nome['campo'] ;?></td>
					<td class="campo1"><?php echo $nome['tipo_de_dado'] ;?></td>
					<td class="campo1"><?php echo $nome['tamanho'] ;?></td>
					<td class="campo1"><?php echo $nome['campo_pk'] ;?></td>
					<td class="campo1"><?php echo $nome['esquema_fk'] ;?></td>
					<td class="campo1"><?php echo $nome['tabela_fk'] ;?></td>
					<td class="campo1"><?php echo $nome['campo_fk'] ;?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<div id='menu_corpo'>
			<?php echo $menuPrograma;?>
		</div>
	</div>
</div>