<div class="container">
	<div class="alert alert-danger">
		<i class="icon-warning-sign"></i>
		<strong>Atenção,</strong>
		<div>
			 Nesta tela você pode fazer configurações de alto risco para o sistema, bastante cuidado ao alterar os dados.
		</div>
	</div>
	<form name="formulario" method="post" action="<?php echo $action;?>" >
		<div class="fc-edicao">
			<h4 class="fc-titulo-especifico"><?php echo $tituloEspecifico;?></h4>
			<div class="tabbable">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#pane1" id="guia_1" data-toggle="tab">Geral</a></li>
					<li><a href="#pane2" id="guia_2" data-toggle="tab">Controle de Acesso</a></li>
					<li><a href="#pane3" id="guia_3" data-toggle="tab">Controle de Menu</a></li>
					<li><a href="#pane4" id="guia_4" data-toggle="tab">Banco de Dados</a></li>
					<li><a href="#pane5" id="guia_5" data-toggle="tab">Diretórios</a></li>
					<li><a href="#pane6" id="guia_6" data-toggle="tab">Arquivos</a></li>
				</ul>
				<div class="tab-content">
					<div id="pane1" class="tab-pane active">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i> <strong><?php echo $textoSistema;?></strong>
							<div class="help">Nas configurações gerais do sistema você poderá definir qual a página inicial do sistema e qual a página de erro do sistema e ainda qual o ambiente que o sistema está funcionando.</div>
						</div>
						<div class="tabela2 well well-small">
							<div class='campo'>
								<label><?php echo $textoNomeSessao;?>:</label>
								<span><?php echo $nomeSessao;?></span>
							</div>
							<div class='campo'>
								<label><?php echo $textoPaginaInicial;?>:</label>
								<span><?php echo $paginaInicial;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_1"></i>
							</div>
							<div class='campo'>
								<label><?php echo $textoPaginaErro;?>:</label>
								<span><?php echo $paginaErro;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_1"></i>
							</div>
							<div class='campo'>
								<label><?php echo $textoAmbiente;?>:</label>
								<span><?php echo $ambiente;?></span>
							</div>
						</div>
					</div>
					<div id="pane2" class="tab-pane">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i> <strong><?php echo $textoControleAcesso;?></strong>
							<div class="help">Nas configurações a seguir você poderá definir qual a classe e qual o método que fará a validação dos acessos do sistema, além de também poder desativar o controle de acesso.</div>
						</div>
						<div class="tabela2 well well-small">
							<div class='campo'>
								<label><?php echo $textoLiberadoCA;?>:</label>
								<span><?php echo $liberadoCA;?></span>
							</div>
							<div class='campo'>
								<label><?php echo $textoClasseCA;?>:</label>
								<span><?php echo $classeCA;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_2"></i>
							</div>
							<div class='campo'>
								<label><?php echo $textoMetodoCA;?>:</label>
								<span><?php echo $metodoCA;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_2"></i>
							</div>
						</div>
					</div>
					<div id="pane3" class="tab-pane">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i>
							<strong><?php echo $textoControleMenu;?></strong>
							<div class="help">Você poderá definir aqui qual a classe e quais os métodos que farão as criações dos menus principal e menu do sistema.</div>
						</div>
						<div class="tabela2 well well-small">
							<div class='campo'>
								<label><?php echo $textoClasseMenu;?>:</label>
								<span><?php echo $classeMenu;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_3"></i>
							</div>
							<div class='campo'>
								<label><?php echo $textoMetodoMenuPrincipal;?>:</label>
								<span><?php echo $metodoMenuPrincipal;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_3"></i>
							</div>
							<div class='campo'>
								<label><?php echo $textoMetodoMenuSistema;?>:</label>
								<span><?php echo $metodoMenuSistema;?></span>
								<i class="teste icon-ok icon-remove" data-guia="#guia_3"></i>
							</div>
						</div>
					</div>
					<div id="pane4" class="tab-pane">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i>
							<strong><?php echo $textoBancos;?></strong>
							<div class="help">Configure aqui as conexões que o sistema possui com os bancos de dados.</div>
						</div>
						<div class="btn-toolbar">
							<div class="btn-group">
								<a id="novaConexao" class="btn btn-success pull-right"><i class="icon-plus-sign icon-white"></i> Nova conexão</a>
							</div>
						</div>
						<table class="table table-striped table-bordered table-hover table-condensed" id="conexoes">
							<thead>
								<tr>
									<th>Nome</th>
									<th>Tipo</th>
									<th>Servidor</th>
									<th>Porta</th>
									<th>Banco</th>
									<th>Usuário</th>
									<th>Senha</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($conexao as $i => $a): ?>
							<div class="d-tr">
								<td><?php echo $conexao[$i];?></td>
								<td class="tipoConn"><?php echo $tipo[$i];?></td>
								<td class="db postgres mysql"><?php echo $servidor[$i];?></td>
								<td class="db postgres mysql"><?php echo $porta[$i];?></td>
								<td class="db postgres mysql oracle sqlite"><?php echo $nome[$i];?></td>
								<td class="db postgres mysql oracle"><?php echo $usuario[$i];?></td>
								<td class="db postgres mysql oracle"><?php echo $senha[$i];?></td>
								<td><div class="teste icon-ok icon-remove teste-db" data-guia="#guia_4"></div></td>
							</div>
							<?php endforeach;?>
							</tbody>
						</table>
					</div>
					<div id="pane5" class="tab-pane">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i>
							<strong><?php echo $textoDiretorios;?></strong>
							<div class="help">Defina abaixo a estrutura de diretórios do sistema.</div>
						</div>
						<table summary="text" class="table table-striped table-bordered table-hover table-condensed">
							<thead>
								<tr>
									<th>Referência</th>
									<th>Caminho</th>
								</tr>
							</thead>
							<tbody id="listagem-diretorios">
								<?php foreach($dirId as $i => $a): ?>
								<tr>
									<td class="campo1"><?php echo $dirId[$i];?><?php echo $dirId[$i]->pegarValue();?>:</td>
									<td class="campo2 campo"><?php echo $dirCaminho[$i];?>
										<span class="teste icon-ok icon-remove" data-guia="#guia_5">&nbsp;&nbsp;&nbsp;&nbsp;</span>
									</td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
					<div id="pane6" class="tab-pane">
						<div class="alert alert-heading">
							<i class="icon-warning-sign"></i>
							<strong><?php echo $textoArquivos;?></strong>
							<div class="help">Nesta etapa você pode definir alguns arquivos do sistema.</div>
						</div>
						<table summary="text" class="table table-striped table-bordered table-hover table-condensed">
							<thead>
								<tr>
									<th>Referência</th>
									<th>Arquivo</th>
								</tr>
							</thead>
							<tbody id="listagem-arquivos">
								<?php foreach($arqId as $i => $a): ?>
								<tr class="campo">
									<td class="campo1"><?php echo $arqId[$i];?><?php echo $arqId[$i]->pegarValue();?>:</td>
									<td class="campo2 campo" arquivo="<?php echo $arqId[$i]->pegarValue();?>"><?php echo $arquivo[$i];?>
										<?php if ($arquivo[$i]->pegarId() == 'inter'): ?><span class="teste icon-ok icon-remove" data-guia="#guia_6">&nbsp;&nbsp;&nbsp;&nbsp;</span><?php endif;?>
									</td>
								</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div><!-- /.tab-content -->
			</div><!-- /.tabbable -->
			<div class="fc-campo-grupo">
				<div id='menu_corpo'>
					<?php echo $menuPrograma;?>
				</div>
			</div>
		</div>
	</form>
</div>